---
platforms:
  - name: molecule-python
    image: python:3.10
    containerfile: Containerfile.j2
    pre_build_image: false

driver:
  options:
    managed: False
    login_cmd_template: "podman exec -ti {instance} bash"
    ansible_connection_options:
      ansible_connection: podman
