---
- name: Add network object
  hosts: localhost
  tasks:
    - name: Add a network host object for this CDO tenant
      ignore_errors: true
      cisco.cdo.net_objects:
        api_key: "{{ lookup('ansible.builtin.env', 'CDO_API_KEY') }}"
        region: "us"
        add:
          name: "ansible-test-host"
          network: "192.168.255.254"
          description: "Ansible Test Host Addition"
      register: new_obj
      failed_when: (new_obj.stderr is defined) and (new_obj.stderr | length > 0)

    - name: Print results
      ansible.builtin.debug:
        msg:
          "{{ new_obj.stdout }}"

    - name: Add a network object for this CDO tenant
      ignore_errors: true
      cisco.cdo.net_objects:
        api_key: "{{ lookup('ansible.builtin.env', 'CDO_API_KEY') }}"
        region: "us"
        add:
          name: "ansible-test-network"
          network: "192.168.255.0/24"
          description: "Ansible Test Network Addition"
      register: new_obj
      failed_when: (new_obj.stderr is defined) and (new_obj.stderr | length > 0)

    - name: Print results
      ansible.builtin.debug:
        msg:
          "{{ new_obj.stdout }}"
