---
- name: Get network objects
  hosts: localhost
  tasks:
    - name: Get all network objects for this CDO tenant
      cisco.cdo.net_objects:
        api_key: "{{ lookup('ansible.builtin.env', 'CDO_API_KEY') }}"
        region: "us"
        gather: {}
      register: net_objs
      failed_when: (net_objs.stderr is defined) and (net_objs.stderr | length > 0)

    - name: Filter Results for desired data using json query
      # Requires python3 package jmespath
      ansible.builtin.debug:
        msg:
          "JSON Filtered Output: {{ net_objs.stdout | community.general.json_query(jmesquery) }}"
      vars:
        jmesquery: >-
          objects[*].{name:name, elements:elements, objectType:objectType, contents:contents, description:description, tags:tags}

    - name: Get all network objects that match the exact filter
      cisco.cdo.net_objects:
        api_key: "{{ lookup('ansible.builtin.env', 'CDO_API_KEY') }}"
        region: "us"
        gather: {
          name: "foo"
        }
      register: exact_net_objs
      failed_when: (exact_net_objs.stderr is defined) and (exact_net_objs.stderr | length > 0)

    - name: Results for exact match
      ansible.builtin.debug:
        msg:
          "Exact Matches: {{ exact_net_objs.stdout }}"

    - name: Get all network objects that match the wildcard filter
      cisco.cdo.net_objects:
        api_key: "{{ lookup('ansible.builtin.env', 'CDO_API_KEY') }}"
        region: "us"
        gather: {
          name: "*foo*"
        }
      register: wildcard_net_objs
      failed_when: (wildcard_net_objs.stderr is defined) and (wildcard_net_objs.stderr | length > 0)

    - name: Results for wildcard match
      ansible.builtin.debug:
        msg:
          "Wildcard Matches: {{ wildcard_net_objs.stdout }}"

    - name: Get all network objects that match the exact filter but no matches
      cisco.cdo.net_objects:
        api_key: "{{ lookup('ansible.builtin.env', 'CDO_API_KEY') }}"
        region: "us"
        gather: {
          name: "zaphod"
        }
      register: exact_net_objs
      failed_when: (exact_net_objs.stderr is defined) and (exact_net_objs.stderr | length > 0)

    - name: Results for exact match
      ansible.builtin.debug:
        msg:
          "Exact Matches: {{ exact_net_objs.stdout }}"
