---
- name: Add ansible inventory to CDO
  hosts: all
  connection: local
  tasks:
    - name: Get this device's settings from host variables (ansible inventory)
      ansible.builtin.set_fact:
        api_key: "{{ lookup('ansible.builtin.env', 'CDO_API_KEY') }}"
        region: "{{ hostvars[inventory_hostname].region }}"
        device_name: "{{ inventory_hostname }}"
        sdc: "{{ hostvars[inventory_hostname].sdc if hostvars[inventory_hostname].sdc is defined }}"
        ipv4: "{{ hostvars[inventory_hostname].ipv4 }}"
        mgmt_port: "{{ hostvars[inventory_hostname].mgmt_port }}"
        device_type: "{{ hostvars[inventory_hostname].device_type }}"
        username: "{{ hostvars[inventory_hostname].username }}"
        password: "{{ hostvars[inventory_hostname].password }}"
        ignore_cert: "{{ hostvars[inventory_hostname].ignore_cert }}"

    - name: Add ASA to CDO
      cisco.cdo.device_inventory:
        api_key: "{{ api_key }}"
        region: "{{ region }}"
        add:
          asa_ios:
            sdc: "{{ sdc }}"
            device_name: "{{ device_name }}"
            ipv4: "{{ ipv4 }} "
            mgmt_port: "{{ mgmt_port }}"
            device_type: "{{ device_type }}"
            username: "{{ username }}"
            password: "{{ password }}"
            ignore_cert: "{{ ignore_cert }}"
      register: added_device
      failed_when: (added_device.stderr is defined) and (added_device.stderr | length > 0)

    - name: Print results
      ansible.builtin.debug:
        msg: "{{ added_device }}"
