FROM python:3.10 AS compile-image

# Required environment vars:
# DEV_BRANCH=xxxx for the git branch under test
# CDO_REGION=xx [us, apj, eu]

# Stage 1: Install all needed libraries and venv
ARG DEV_BRANCH
RUN apt-get update
RUN python -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"
RUN pip install --upgrade pip && pip install ansible ansible-lint
RUN mkdir -p /opt/venv/app/collections/ansible_collections/cisco
WORKDIR /opt/venv/app/collections/ansible_collections/cisco
RUN git clone https://github.com/CiscoDevNet/ansible-cisco-cdo.git
RUN cd /opt/venv/app/collections/ansible_collections/cisco/ansible-cisco-cdo && git checkout ${DEV_BRANCH}
RUN mv ansible-cisco-cdo cdo
RUN pip install -r cdo/requirements.txt

# Stage 2: Final stage build image
FROM python:3.10 AS build-image
COPY --from=compile-image /opt/venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"
ENV CDO_REGION=${CDO_REGION}
ENV ANSIBLE_COLLECTIONS_PATHS=/opt/venv/app/collections
WORKDIR /opt/venv/app/collections/ansible_collections/cisco/cdo
