---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml

platforms:
  - name: ElPaso
    image: python:3.10
    containerfile: Containerfile.j2
    pre_build_image: false
  # - name: ElPaso

  - name: Galveston
    image: python:3.10
    containerfile: Containerfile.j2
    pre_build_image: false

  - name: Austin
    image: python:3.10
    containerfile: Containerfile.j2
    pre_build_image: false

  - name: Amarillo
    image: python:3.10
    containerfile: Containerfile.j2
    pre_build_image: false

driver:
  options:
    managed: false
    login_cmd_template: "podman exec -ti {instance} bash"
    ansible_connection_options:
      ansible_connection: podman

provisioner:
  name: ansible
  inventory:
    host_vars:
      ElPaso:
        ansible_python_interpreter: /usr/local/bin/python
        device_type: ftd
        onboard_method: cli
        access_control_policy: Default Access Control Policy
        is_virtual: true
        performance_tier: FTDv10
        license:
          - BASE
          - THREAT
          - URLFilter
          - MALWARE
          - PLUS
      Galveston:
        ansible_python_interpreter: /usr/local/bin/python
        device_type: ftd
        onboard_method: ltp
        serial: JADXXXXXXXX
        password: Admin123!!
        access_control_policy: Default Access Control Policy
        is_virtual: true
        performance_tier: FTDv10
        license:
          - BASE
          - THREAT
          - URLFilter
          - MALWARE
          - PLUS
      Austin:
        ansible_python_interpreter: /usr/local/bin/python
        device_type: asa
        ipv4: 172.30.4.101
        mgmt_port: 8443
        sdc: CDO_cisco_aahackne-SDC-1
        username: cisco
        password: Admin123!!
        ignore_cert: true
      Amarillo:
        ansible_python_interpreter: /usr/local/bin/python
        device_type: asa
        ipv4: 172.30.4.119
        mgmt_port: 8443
        sdc: CDO_cisco_aahackne-SDC-1
        username: cisco
        password: Admin123!!
        ignore_cert: true