---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml

platforms:
  - name: molecule-python
    image: python:3.10
    containerfile: Containerfile.j2
    pre_build_image: false
  # - name: ElPaso

driver:
  options:
    managed: false
    login_cmd_template: "podman exec -ti {instance} bash"
    ansible_connection_options:
      ansible_connection: podman

provisioner:
  name: ansible
  inventory:
    host_vars:
      molecule-python:
        ansible_python_interpreter: /usr/local/bin/python
        device_type: ftd
        onboard_method: cli
        access_control_policy: Default Access Control Policy
        is_virtual: true
        performance_tier: FTDv10
        license:
          - BASE
          - THREAT
          - URLFilter
          - MALWARE
          - PLUS
