---
- name: Run CLI Commands on ASA and IOS
  hosts: all
  connection: local
  tasks:
    - name: Run ASA/IOS CLI Commands and return output if any
      when: hostvars[inventory_hostname].device_type == "asa" or hostvars[inventory_hostname].device_type == "ios"
      cisco.cdo.cmd:
        api_key: "{{ lookup('ansible.builtin.env', 'CDO_API_KEY') }}"
        region: "{{ lookup('ansible.builtin.env', 'CDO_REGION') }}"
        apply_template:
          device_name: "{{ inventory_hostname }}"
          config: "{{ hostvars[inventory_hostname].config }}"

      register: command_output
      failed_when: (added_device.stderr is defined) and (added_device.stderr | length > 0)

    - name: Print results
      ansible.builtin.debug:
        # msg: "{{ command_output.stdout.split('\n') }}"
        msg: "{{ command_output }}"
