---
- name: Deploy pending device changes
  hosts: localhost
  tasks:
    - name: Deploy pending device changes
      cisco.cdo.deploy:
        api_key: "{{ lookup('ansible.builtin.env', 'CDO_API_KEY') }}"
        region: "us"
        deploy:
          device_type: "all"
          timeout: 20
          interval: 2
      register: deploy
      failed_when: (deploy.stderr is defined) and (deploy.stderr | length > 0)

    - name: Print All Results
      ansible.builtin.debug:
        msg:
          "{{ deploy }}"
