---
- name: Get device inventory details
  hosts: localhost
  tasks:
    - name: Get the pending deploy for devices in this tenant
      cisco.cdo.deploy:
        api_key: "{{ lookup('ansible.builtin.env', 'CDO_API_KEY') }}"
        region: "us"
        pending:
          device_type: "all"
      register: pending_deploy
      failed_when: (pending_deploy.stderr is defined) and (pending_deploy.stderr | length > 0)

    - name: Print All Results for all devices, all fields
      ansible.builtin.debug:
        msg:
          "{{ pending_deploy }}"
