---
- name: Delete ASA Device from CDO inventory
  hosts: localhost
  tasks:
    - name: Delete IOS Device from CDO inventory
      cisco.cdo.inventory:
        api_key: "{{ lookup('ansible.builtin.env', 'CDO_API_KEY') }}"
        region: 'us'
        delete:
          name: 'Austin'
          device_type: 'asa'
      register: deleted_device
      failed_when: (deleted_device.stderr is defined) and (deleted_device.stderr | length > 0)

    - name: Print results
      ansible.builtin.debug:
        msg:
          "{{ deleted_device }}"
