---
- name: Get network objects
  hosts: localhost
  tasks:
    - name: Get all network objects for this CDO tenant
      cisco.cdo.net_objects:
        api_key: "{{ lookup('ansible.builtin.env', 'CDO_API_KEY') }}"
        region: "us"
        net_objects: {}
      register: net_objs
      failed_when: (net_objs.stderr is defined) and (net_objs.stderr | length > 0)

    - name: Filter Results for desired data using json query
      # Requires python3 package jmespath
      ansible.builtin.debug:
        msg:
          "{{ net_objs.stdout | community.general.json_query(jmesquery) }}"
      vars:
        jmesquery: >-
          objects[*].{name:name, elements:elements, objectType:objectType, contents:contents, description:description, tags:tags}

    - name: Get all network objects that match the exact filter
      cisco.cdo.net_objects:
        api_key: "{{ lookup('ansible.builtin.env', 'CDO_API_KEY') }}"
        region: "us"
        net_objects: {
          filter: "foo"
        }
      register: net_objs
      failed_when: (net_objs.stderr is defined) and (net_objs.stderr | length > 0)

    - name: Get all network objects that match the wildcard filter
      cisco.cdo.net_objects:
        api_key: "{{ lookup('ansible.builtin.env', 'CDO_API_KEY') }}"
        region: "us"
        net_objects: {
          filter: "*foo*"
        }
      register: net_objs
      failed_when: (net_objs.stderr is defined) and (net_objs.stderr | length > 0)
